//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.13 at 10:53:57 AM WAT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://kelmorgan.com/firstsoapservice/countries", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.kelmorgan.consumesoapservice.wsdl;
